In [141]:
words = open('names.txt','r').read().splitlines()

In [142]:
words[:10]

['emma',
 'olivia',
 'ava',
 'isabella',
 'sophia',
 'charlotte',
 'mia',
 'amelia',
 'harper',
 'evelyn']

In [143]:
len(words)

32033

In [144]:
min(len(w) for w in words)

2

In [145]:
max(len(w) for w in words)

15

In [146]:
b={}
for w in words:
    chs=['<S>']+list(w)+['<E>']
    for ch1, ch2 in zip(chs,chs[1:]):
        bigram=(ch1,ch2)
        b[bigram]= b.get(bigram,0)+1
        

In [147]:
sorted(b.items(),key=lambda kv:-kv[1])

[(('n', '<E>'), 6763),
 (('a', '<E>'), 6640),
 (('a', 'n'), 5438),
 (('<S>', 'a'), 4410),
 (('e', '<E>'), 3983),
 (('a', 'r'), 3264),
 (('e', 'l'), 3248),
 (('r', 'i'), 3033),
 (('n', 'a'), 2977),
 (('<S>', 'k'), 2963),
 (('l', 'e'), 2921),
 (('e', 'n'), 2675),
 (('l', 'a'), 2623),
 (('m', 'a'), 2590),
 (('<S>', 'm'), 2538),
 (('a', 'l'), 2528),
 (('i', '<E>'), 2489),
 (('l', 'i'), 2480),
 (('i', 'a'), 2445),
 (('<S>', 'j'), 2422),
 (('o', 'n'), 2411),
 (('h', '<E>'), 2409),
 (('r', 'a'), 2356),
 (('a', 'h'), 2332),
 (('h', 'a'), 2244),
 (('y', 'a'), 2143),
 (('i', 'n'), 2126),
 (('<S>', 's'), 2055),
 (('a', 'y'), 2050),
 (('y', '<E>'), 2007),
 (('e', 'r'), 1958),
 (('n', 'n'), 1906),
 (('y', 'n'), 1826),
 (('k', 'a'), 1731),
 (('n', 'i'), 1725),
 (('r', 'e'), 1697),
 (('<S>', 'd'), 1690),
 (('i', 'e'), 1653),
 (('a', 'i'), 1650),
 (('<S>', 'r'), 1639),
 (('a', 'm'), 1634),
 (('l', 'y'), 1588),
 (('<S>', 'l'), 1572),
 (('<S>', 'c'), 1542),
 (('<S>', 'e'), 1531),
 (('j', 'a'), 1473),
 (

In [148]:
import torch

In [149]:
a=torch.zeros((3,5),dtype=torch.int32)
a

tensor([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]], dtype=torch.int32)

In [150]:
a.dtype

torch.int32

In [151]:
N=torch.zeros((27,27),dtype=torch.int32)

In [152]:
chars=sorted(list(set("".join(words))))
stoi={s:i+1 for i,s in enumerate(chars)}
stoi['.']=0

In [153]:
stoi

{'a': 1,
 'b': 2,
 'c': 3,
 'd': 4,
 'e': 5,
 'f': 6,
 'g': 7,
 'h': 8,
 'i': 9,
 'j': 10,
 'k': 11,
 'l': 12,
 'm': 13,
 'n': 14,
 'o': 15,
 'p': 16,
 'q': 17,
 'r': 18,
 's': 19,
 't': 20,
 'u': 21,
 'v': 22,
 'w': 23,
 'x': 24,
 'y': 25,
 'z': 26,
 '.': 0}

In [154]:
itos={s:i for i,s in stoi.items()}
itos

{1: 'a',
 2: 'b',
 3: 'c',
 4: 'd',
 5: 'e',
 6: 'f',
 7: 'g',
 8: 'h',
 9: 'i',
 10: 'j',
 11: 'k',
 12: 'l',
 13: 'm',
 14: 'n',
 15: 'o',
 16: 'p',
 17: 'q',
 18: 'r',
 19: 's',
 20: 't',
 21: 'u',
 22: 'v',
 23: 'w',
 24: 'x',
 25: 'y',
 26: 'z',
 0: '.'}

In [155]:
for w in words:
    chs=['.']+list(w)+['.']
    for ch1, ch2 in zip(chs,chs[1:]):
        ix1=stoi[ch1]
        ix2=stoi[ch2]
        N[ix1,ix2]+=1

In [156]:
N

tensor([[   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
         1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
          134,  535,  929],
        [6640,  556,  541,  470, 1042,  692,  134,  168, 2332, 1650,  175,  568,
         2528, 1634, 5438,   63,   82,   60, 3264, 1118,  687,  381,  834,  161,
          182, 2050,  435],
        [ 114,  321,   38,    1,   65,  655,    0,    0,   41,  217,    1,    0,
          103,    0,    4,  105,    0,    0,  842,    8,    2,   45,    0,    0,
            0,   83,    0],
        [  97,  815,    0,   42,    1,  551,    0,    2,  664,  271,    3,  316,
          116,    0,    0,  380,    1,   11,   76,    5,   35,   35,    0,    0,
            3,  104,    4],
        [ 516, 1303,    1,    3,  149, 1283,    5,   25,  118,  674,    9,    3,
           60,   30,   31,  378,    0,    1,  424,   29,    4,   92,   17,   23,
            0,  317,    1],
        [3983,  679,  121,  153,  384, 1271,   82,

In [157]:
type(N[3,3])

torch.Tensor

In [158]:
N[0]

tensor([   0, 4410, 1306, 1542, 1690, 1531,  417,  669,  874,  591, 2422, 2963,
        1572, 2538, 1146,  394,  515,   92, 1639, 2055, 1308,   78,  376,  307,
         134,  535,  929], dtype=torch.int32)

In [159]:
p=N[0].float()
p/=p.sum()
print(p) #probablity 

tensor([0.0000, 0.1377, 0.0408, 0.0481, 0.0528, 0.0478, 0.0130, 0.0209, 0.0273,
        0.0184, 0.0756, 0.0925, 0.0491, 0.0792, 0.0358, 0.0123, 0.0161, 0.0029,
        0.0512, 0.0642, 0.0408, 0.0024, 0.0117, 0.0096, 0.0042, 0.0167, 0.0290])


In [160]:
g=torch.Generator().manual_seed(2147483647)
ix=torch.multinomial(p,num_samples=1,replacement=True,generator=g).item()
itos[ix]

'j'

In [161]:
ge=torch.Generator().manual_seed(2147483647)
pe=torch.rand(3,generator=ge)
pe=pe/pe.sum()
pe

tensor([0.6064, 0.3033, 0.0903])

In [162]:
torch.multinomial(pe,num_samples=100,replacement=True,generator=g)

tensor([1, 1, 1, 2, 0, 0, 2, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 2, 0,
        0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 1,
        0, 0, 1, 1])

In [163]:
P = N.float()
P.sum(1,keepdim=True)

tensor([[32033.],
        [33885.],
        [ 2645.],
        [ 3532.],
        [ 5496.],
        [20423.],
        [  905.],
        [ 1927.],
        [ 7616.],
        [17701.],
        [ 2900.],
        [ 5040.],
        [13958.],
        [ 6642.],
        [18327.],
        [ 7934.],
        [ 1026.],
        [  272.],
        [12700.],
        [ 8106.],
        [ 5570.],
        [ 3135.],
        [ 2573.],
        [  929.],
        [  697.],
        [ 9776.],
        [ 2398.]])

In [164]:
P = N.float()
P=P/P.sum(1,keepdim=True)
P

tensor([[0.0000e+00, 1.3767e-01, 4.0770e-02, 4.8138e-02, 5.2758e-02, 4.7794e-02,
         1.3018e-02, 2.0885e-02, 2.7284e-02, 1.8450e-02, 7.5610e-02, 9.2498e-02,
         4.9074e-02, 7.9231e-02, 3.5776e-02, 1.2300e-02, 1.6077e-02, 2.8720e-03,
         5.1166e-02, 6.4153e-02, 4.0833e-02, 2.4350e-03, 1.1738e-02, 9.5839e-03,
         4.1832e-03, 1.6702e-02, 2.9001e-02],
        [1.9596e-01, 1.6408e-02, 1.5966e-02, 1.3870e-02, 3.0751e-02, 2.0422e-02,
         3.9546e-03, 4.9579e-03, 6.8821e-02, 4.8694e-02, 5.1645e-03, 1.6763e-02,
         7.4605e-02, 4.8222e-02, 1.6048e-01, 1.8592e-03, 2.4199e-03, 1.7707e-03,
         9.6326e-02, 3.2994e-02, 2.0274e-02, 1.1244e-02, 2.4613e-02, 4.7514e-03,
         5.3711e-03, 6.0499e-02, 1.2838e-02],
        [4.3100e-02, 1.2136e-01, 1.4367e-02, 3.7807e-04, 2.4575e-02, 2.4764e-01,
         0.0000e+00, 0.0000e+00, 1.5501e-02, 8.2042e-02, 3.7807e-04, 0.0000e+00,
         3.8941e-02, 0.0000e+00, 1.5123e-03, 3.9698e-02, 0.0000e+00, 0.0000e+00,
         3.1834e-

In [165]:
#predict names
P = (N+1).float()
P=P/P.sum(1,keepdim=True)
g=torch.Generator().manual_seed(2147483647)
for i in range(20):
    ix=0
    out=[]
    while True:
        p=P[ix]
        #p=N[ix].float()
        #p/=p.sum()
        ix=torch.multinomial(p,num_samples=1,replacement=True,generator=g).item()
        out.append(itos[ix])
        if ix==0:
            break
    print(''.join(out))

junide.
janasah.
p.
cony.
a.
nn.
kohin.
tolian.
juee.
ksahnaauranilevias.
dedainrwieta.
ssonielylarte.
faveumerifontume.
phynslenaruani.
core.
yaenon.
ka.
jabdinerimikimaynin.
anaasn.
ssorionsush.


In [166]:
#evaluate quality of the model
log_likelihood=0.0
n=0
#for w in words:
for w in ['jayant']:
    chs=['.']+list(w)+['.']
    for ch1, ch2 in zip(chs,chs[1:]):
        ix1=stoi[ch1]
        ix2=stoi[ch2]
        prob = P[ix1,ix2]
        logprob = torch.log(prob)
        log_likelihood += logprob
        n+=1
        print(f'{ch1}-{ch2}:{prob:.4f}{logprob:.4f}')
print(f'{log_likelihood=}')
nll = -log_likelihood
print(f'{nll=}')
print(f'{nll/n}')

.-j:0.0756-2.5826
j-a:0.5036-0.6860
a-y:0.0605-2.8054
y-a:0.2187-1.5200
a-n:0.1604-1.8302
n-t:0.0242-3.7218
t-.:0.0865-2.4479
log_likelihood=tensor(-15.5939)
nll=tensor(15.5939)
2.227701425552368


In [167]:
xs,ys=[],[]
for w in ['jayant']:
    chs=['.']+list(w)+['.']
    for ch1, ch2 in zip(chs,chs[1:]):
        ix1=stoi[ch1]
        ix2=stoi[ch2]
        print(ch1,ch2)
        xs.append(ix1)
        ys.append(ix2)
xs=torch.tensor(xs)
ys=torch.tensor(ys)

. j
j a
a y
y a
a n
n t
t .


In [168]:
xs

tensor([ 0, 10,  1, 25,  1, 14, 20])

In [169]:
ys

tensor([10,  1, 25,  1, 14, 20,  0])

In [170]:
import torch.nn.functional as F
xenc=F.one_hot(xs,num_classes=27).float()
xenc

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [171]:
xenc.shape

torch.Size([7, 27])

In [172]:
W=torch.randn((27,27))
W

tensor([[-2.0697e+00, -3.2445e-01,  1.4161e+00, -4.7357e-01, -8.8961e-01,
          1.5085e-01,  1.2570e+00, -2.3712e-01, -7.1645e-01,  5.6363e-01,
          4.4379e-01,  1.2047e+00,  8.2102e-01,  4.2101e-01, -4.0262e-01,
         -4.6120e-01, -2.6149e-01, -1.2943e-01,  3.2679e-01,  3.1930e-01,
         -5.7461e-01,  4.1392e-01,  7.8171e-01, -1.5275e+00,  3.7455e-01,
         -5.6506e-01,  5.5935e-02],
        [-2.8244e-01, -7.7824e-01, -2.9617e-02,  4.7092e-01,  2.7717e-01,
         -4.8962e-01,  1.6472e+00, -1.3033e+00, -1.0559e-02,  3.3616e-03,
         -1.7322e+00,  1.5175e+00,  6.8383e-01, -8.8821e-01,  3.9723e-01,
         -6.9486e-01,  6.6872e-01, -1.5828e+00,  1.4511e-01, -1.9601e-01,
          1.0877e-01,  2.0652e+00,  6.0081e-01, -1.2854e+00, -2.6462e-01,
         -1.7216e+00,  1.0287e+00],
        [-1.2363e+00,  5.4145e-01,  1.3587e+00, -5.8785e-01,  4.2655e-01,
         -1.2069e+00,  1.5950e-01, -4.0087e-01, -4.3967e-01,  3.3466e-01,
         -3.0213e+00,  1.0181e+00, -9.01

In [173]:
logits = xenc @ W
# @ is matrix multiplication operator in pytorch
logits

tensor([[-2.0697, -0.3245,  1.4161, -0.4736, -0.8896,  0.1508,  1.2570, -0.2371,
         -0.7165,  0.5636,  0.4438,  1.2047,  0.8210,  0.4210, -0.4026, -0.4612,
         -0.2615, -0.1294,  0.3268,  0.3193, -0.5746,  0.4139,  0.7817, -1.5275,
          0.3745, -0.5651,  0.0559],
        [-0.3394,  0.4466,  0.9023, -0.4656, -0.1084,  0.5958, -0.9519,  2.2865,
         -0.1311, -0.3058,  0.3639,  0.7136, -1.3469, -0.1757, -0.3835,  0.1746,
          1.2338, -0.9893,  0.3200,  1.0993, -2.3033, -1.9950,  1.1160, -1.0906,
         -0.7459, -2.9333, -0.4324],
        [-0.2824, -0.7782, -0.0296,  0.4709,  0.2772, -0.4896,  1.6472, -1.3033,
         -0.0106,  0.0034, -1.7322,  1.5175,  0.6838, -0.8882,  0.3972, -0.6949,
          0.6687, -1.5828,  0.1451, -0.1960,  0.1088,  2.0652,  0.6008, -1.2854,
         -0.2646, -1.7216,  1.0287],
        [ 0.6233, -1.0611,  2.2469,  0.9171, -0.4569,  0.6163,  0.4850, -0.6039,
         -0.6307,  0.6588, -1.2014,  0.1080,  0.8572,  0.4714,  0.2826,  2.2576

In [174]:
counts=(xenc @ W).exp()
counts

tensor([[0.1262, 0.7229, 4.1211, 0.6228, 0.4108, 1.1628, 3.5149, 0.7889, 0.4885,
         1.7570, 1.5586, 3.3356, 2.2728, 1.5235, 0.6686, 0.6305, 0.7699, 0.8786,
         1.3865, 1.3762, 0.5629, 1.5127, 2.1852, 0.2171, 1.4543, 0.5683, 1.0575],
        [0.7122, 1.5630, 2.4653, 0.6277, 0.8973, 1.8146, 0.3860, 9.8400, 0.8772,
         0.7366, 1.4390, 2.0413, 0.2600, 0.8388, 0.6815, 1.1908, 3.4342, 0.3718,
         1.3772, 3.0020, 0.0999, 0.1360, 3.0526, 0.3360, 0.4743, 0.0532, 0.6489],
        [0.7539, 0.4592, 0.9708, 1.6015, 1.3194, 0.6129, 5.1922, 0.2716, 0.9895,
         1.0034, 0.1769, 4.5609, 1.9814, 0.4114, 1.4877, 0.4991, 1.9517, 0.2054,
         1.1562, 0.8220, 1.1149, 7.8872, 1.8236, 0.2765, 0.7675, 0.1788, 2.7973],
        [1.8652, 0.3461, 9.4580, 2.5020, 0.6332, 1.8520, 1.6242, 0.5467, 0.5322,
         1.9326, 0.3008, 1.1140, 2.3566, 1.6022, 1.3265, 9.5604, 0.4315, 0.6518,
         1.2369, 0.7230, 0.2293, 0.7295, 2.0959, 1.1532, 0.8635, 8.9395, 1.4543],
        [0.7539, 0.4592,

In [175]:
probs = counts/counts.sum(1,keepdims= True)
print(counts.shape)
print(counts.sum(1,keepdims= True).shape)
print(probs.shape)
print(probs)

torch.Size([7, 27])
torch.Size([7, 1])
torch.Size([7, 27])
tensor([[0.0035, 0.0203, 0.1155, 0.0175, 0.0115, 0.0326, 0.0985, 0.0221, 0.0137,
         0.0493, 0.0437, 0.0935, 0.0637, 0.0427, 0.0187, 0.0177, 0.0216, 0.0246,
         0.0389, 0.0386, 0.0158, 0.0424, 0.0613, 0.0061, 0.0408, 0.0159, 0.0296],
        [0.0181, 0.0397, 0.0626, 0.0159, 0.0228, 0.0461, 0.0098, 0.2500, 0.0223,
         0.0187, 0.0366, 0.0519, 0.0066, 0.0213, 0.0173, 0.0303, 0.0873, 0.0094,
         0.0350, 0.0763, 0.0025, 0.0035, 0.0776, 0.0085, 0.0121, 0.0014, 0.0165],
        [0.0183, 0.0111, 0.0235, 0.0388, 0.0320, 0.0148, 0.1258, 0.0066, 0.0240,
         0.0243, 0.0043, 0.1105, 0.0480, 0.0100, 0.0360, 0.0121, 0.0473, 0.0050,
         0.0280, 0.0199, 0.0270, 0.1911, 0.0442, 0.0067, 0.0186, 0.0043, 0.0678],
        [0.0333, 0.0062, 0.1687, 0.0446, 0.0113, 0.0330, 0.0290, 0.0098, 0.0095,
         0.0345, 0.0054, 0.0199, 0.0420, 0.0286, 0.0237, 0.1705, 0.0077, 0.0116,
         0.0221, 0.0129, 0.0041, 0.0130, 0.0374

In [176]:
probs[0].sum()

tensor(1.0000)

In [177]:
xs

tensor([ 0, 10,  1, 25,  1, 14, 20])

In [178]:
ys

tensor([10,  1, 25,  1, 14, 20,  0])

In [179]:
#randomly initialize 27 neurons weights each neuron recieves 27 inputs
g=torch.Generator().manual_seed(2147483647)
W=torch.randn((27,27),generator=g)

In [181]:
#forward pass
xenc=F.one_hot(xs,num_classes=27).float() #input to network:one_hot encoding
logits=xenc@W #predict log counts
counts=logits.exp() #counts, equivalent to N
probs = counts / counts.sum(1,keepdims=True) #probabilities
loss=-probs[torch.arange(7),ys].log().mean()+ 0.01*(W**2).mean()

In [182]:
print(loss.item())

3.64088773727417


In [208]:
# create the dataset
xs, ys = [], []
for w in words:
  chs = ['.'] + list(w) + ['.']
  for ch1, ch2 in zip(chs, chs[1:]):
    ix1 = stoi[ch1]
    ix2 = stoi[ch2]
    xs.append(ix1)
    ys.append(ix2)
xs = torch.tensor(xs)
ys = torch.tensor(ys)
num = xs.nelement()
print('number of examples: ', num)

# initialize the 'network'
g = torch.Generator().manual_seed(2147483647)
W = torch.randn((27, 27), generator=g, requires_grad=True)

number of examples:  228146


In [214]:
# gradient descent
for k in range(25):
  
  # forward pass #softmax function
    xenc = F.one_hot(xs, num_classes=27).float() # input to the network: one-hot encoding
    logits = xenc @ W # predict log-counts
    counts = logits.exp() # counts, equivalent to N
    probs = counts / counts.sum(1, keepdims=True) # probabilities for next character
    loss = -probs[torch.arange(num), ys].log().mean() + 0.01*(W**2).mean()
    print(loss.item())
  
  # backward pass
    W.grad = None # set to zero the gradient
    loss.backward()
  
  # update
    W.data += -50 * W.grad
W.grad  

2.529768228530884
2.527860164642334
2.5260636806488037
2.5243701934814453
2.522773265838623
2.52126407623291
2.519836664199829
2.5184857845306396
2.5172054767608643
2.515990734100342
2.5148372650146484
2.5137410163879395
2.51269793510437
2.511704921722412
2.5107579231262207
2.509855031967163
2.5089924335479736
2.5081686973571777
2.507380485534668
2.5066256523132324
2.5059030055999756
2.5052106380462646
2.5045459270477295
2.5039076805114746
2.503295421600342


tensor([[ 2.7402e-04, -7.3854e-06, -8.3105e-06, -8.0962e-06, -7.9986e-06,
         -8.1088e-06, -2.7070e-05, -9.8294e-06, -9.0726e-06, -1.0086e-05,
         -7.6907e-06, -7.5704e-06, -8.0741e-06, -7.6623e-06, -8.5095e-06,
         -6.6660e-06, -9.8740e-06,  2.6821e-07, -8.0300e-06, -7.8175e-06,
         -8.3101e-06,  1.1569e-04, -3.1048e-05, -1.3829e-06,  6.0310e-05,
         -9.9011e-06, -8.9174e-06],
        [-2.2677e-05, -3.2262e-05, -3.0407e-05, -3.5297e-05, -2.5764e-05,
         -2.8351e-05,  5.4357e-05, -2.7544e-06, -2.3613e-05, -2.4267e-05,
          2.3182e-05, -3.1849e-05, -2.3493e-05, -2.4290e-05, -2.2792e-05,
          1.1495e-04,  1.0372e-04,  7.2446e-05, -2.3185e-05, -2.5466e-05,
         -2.8366e-05, -3.1260e-05, -2.7111e-05,  2.4022e-05,  1.7283e-05,
         -2.3821e-05, -3.7771e-05],
        [-1.3662e-04, -3.6481e-04,  3.3176e-05,  1.3524e-04, -1.5973e-04,
         -1.3712e-04,  1.1335e-04,  8.7450e-05, -1.0283e-04, -5.2377e-04,
          1.6620e-04,  3.9541e-05,  4.08

In [215]:
# finally, sample from the 'neural net' model
g = torch.Generator().manual_seed(2147483647)

for i in range(5):
  
  out = []
  ix = 0
  while True:
    # BEFORE:
    # p = P[ix]
    # NOW:
    xenc = F.one_hot(torch.tensor([ix]), num_classes=27).float()
    logits = xenc @ W # predict log-counts
    counts = logits.exp() # counts, equivalent to N
    p = counts / counts.sum(1, keepdims=True) # probabilities for next character
    # ----------
    ix = torch.multinomial(p, num_samples=1, replacement=True, generator=g).item()
    out.append(itos[ix])
    if ix == 0:
      break
  print(out)
  print(''.join(out))

['j', 'u', 'n', 'i', 'd', 'e', '.']
junide.
['j', 'a', 'n', 'a', 's', 'a', 'h', '.']
janasah.
['p', 'x', 'z', 'f', 'a', 'y', '.']
pxzfay.
['a', '.']
a.
['n', 'n', '.']
nn.
